# Generated by Django 4.0.5 on 2022-06-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_post_text_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='post',
        ),
    ]
